on:
  workflow_dispatch:
  schedule:
  - cron: '5 9 * * 5,6'
jobs:
  Phigros:
    runs-on: ubuntu-22.04
    steps:
    - run: sh main.sh
    
    - name: Archive output
      uses: actions/upload-artifact@v4
      with:
        name: Phigros
        path: ./
